raw:
  year:    "2022"
  run:     "008294"
  files:   "101-151"
  initial: "${tpl.dir}/align_2022_3ST.txt"
  format:  "Y${raw.year}_R${raw.run}_F${raw.files}"

data:
  dir: "/eos/home-s/shunlian/Alignment/data/${raw.format}"
  config: "${data.dir}/config.yaml"

set:
  dir:  "${data.dir}/set{set}_iters{iters}_st{reco}_{comment}"
  iter: "${set.dir}/iter{i}"
  reco: "${set.iter}/reco"
  pede: "${set.iter}/pede{p}"
  steps:
    - iters: 15
      reco: 3
      comment: "fix2layers"
      pedes:
        - ["IFT", 210, 410]
        - ["IFT", 200, 220, 300, 310, 320, 400, 420]
    - iters: 15
      reco: 4
      comment: "fixlocal"
      pedes:
        - ["local", "3ST"]
    - iters: 15
      reco: 4
      comment: "fixglobal"
      pedes:
        - ["global", "3ST"]

dag:
  dir:      "${src.dir}/dag_files/${raw.format}"
  file:     "${dag.dir}/alignment.dag"
  recoexe:  "${dag.dir}/runAlignment.sh"
  milleexe: "${dag.dir}/runMillepede.sh"
  iter:
    dir:      "${dag.dir}/iter{iter}"
    recojob:  "reco_iter{iter}_{file}"
    recosub:  "${dag.iter.dir}/reco_iter{iter}_{file}.sub"
    millejob: "millepede_iter{iter}"
    millesub: "${dag.iter.dir}/millepede_iter{iter}.sub"
    logs:
      dir:      "${dag.iter.dir}/logs_iter{iter}"
      recoerr:  "${dag.iter.logs.dir}/reco_iter{iter}_{file}.err"
      recolog:  "${dag.iter.logs.dir}/reco_iter{iter}_{file}.log"
      recoout:  "${dag.iter.logs.dir}/reco_iter{iter}_{file}.out"
      milleerr: "${dag.iter.logs.dir}/millepede_iter{iter}.err"
      millelog: "${dag.iter.logs.dir}/millepede_iter{iter}.log"
      milleout: "${dag.iter.logs.dir}/millepede_iter{iter}.out"

tpl:
  dir: "/afs/cern.ch/user/s/shunlian/alignment/templates"
  recosub: "${tpl.dir}/reco.sub.tpl"
  recoexe: "${tpl.dir}/runAlignment.sh"
  millesub: "${tpl.dir}/mille.sub.tpl"
  milleexe: "${tpl.dir}/runMillepede.sh"

src:
  dir: "/afs/cern.ch/user/s/shunlian/alignment"

env:
  calypso:
    asetup: "/eos/home-s/shunlian/Alignment/calypso/asetup.faser"
    setup: "/eos/home-s/shunlian/Alignment/install/setup.sh"
  pede: "/eos/home-s/shunlian/Environments/apps/Millepede-II/V04-17-05"
  root: "/cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.36.04/x86_64-almalinux9.6-gcc115-opt/bin/thisroot.sh"